### PR TITLE
e2: bor-mainnet fix broken v1-054600-054700-borspans.seg 

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by yperbasis** [comment]
It's not helping unfortunatelly:
```
[INFO] [05-08|07:08:08.886] Build info                               git_branch=e2_bor_mainnet_borspan git_tag=v2.54.0-819-g665c9a180c git_commit=665c9a180c54744d6b1f490c0714aae8296d2201
...
[INFO] [05-08|07:11:11.090] [snapshots] no metadata yet              files=1 list=v1-054600-054700-borspans.seg
```

**Comment by AskAlexSharov** [comment]
> It's not helping unfortunatelly:
> 
> ```
> [INFO] [05-08|07:08:08.886] Build info                               git_branch=e2_bor_mainnet_borspan git_tag=v2.54.0-819-g665c9a180c git_commit=665c9a180c54744d6b1f490c0714aae8296d2201
> ...
> [INFO] [05-08|07:11:11.090] [snapshots] no metadata yet              files=1 list=v1-054600-054700-borspans.seg
> ```

existing local files have higher priority. you need `rm snapshots/v1-054600-054700-borspans.seg*` and restart.

**Comment by yperbasis** [comment]
> existing local files have higher priority. you need `rm snapshots/v1-054600-054700-borspans.seg*` and restart.

No, it's not that. I wiped out the datadir. There are no `snapshots/v1-054600-054700-borspans.seg*` files.

**Comment by yperbasis** [comment]
but `no metadata yet              files=1 list=v1-054600-054700-borspans.seg` persists

**Comment by AskAlexSharov** [comment]
then i removing all bor files since `v1-054600-054700`

**Comment by yperbasis** [comment]
> then i removing all bor files since `v1-054600-054700`

still no luck :(

**Review by yperbasis — APPROVED** [review]

**Pull request merged**
